version: '3.4'

services:
  my-mongo:
    container_name: 'mongo'
    image: mongo:latest
    ports:
      - "27017:27017"
  my-server:
    container_name: 'my-server'
    image: mjudnauszy/scala-play-angular-shop_my-server:latest
    environment:
      - MONGO_HOST=my-mongo
    depends_on:
      - my-mongo
    ports:
      - "9000:9000"
    expose:
      - "9000"
  my-client:
    container_name: 'my-client'
    image: mjudnauszy/scala-play-angular-shop_my-client:latest
    depends_on:
      - my-server
    ports:
      - "8080:4200"
    expose:
      - "4200"